version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0303hecate456
      MYSQL_DATABASE: agroquimicos_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql # Mount SQL file
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysql_data: